### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-renderers#54]
#52 broke renderering of [this](http://services.arcgis.com/uCXeTVveQzP4IIcx/arcgis/rest/services/VaquitaProtection/FeatureServer/0)  unique value renderer (no default symbol) service.  i stepped through the code and am temporarily stumped as to *how*.

on a side note, it doesn't look like we ever interpreted the supplied `transparency` correctly.

**Comment by kneemer** [comment]
I'll take a look later at what I broke when I'm at a computer.  

I'm not sure what you mean in the side note about the transparency. I know I have set symbol transparencies on the service before and they were successful. The map level transparency doesn't work because it is not supplied with the renderer information.

**Comment by jgravois** [comment]
no worries.  the example url i provided defines FeatureLayer level transparency (not at the individual renderer level, but for the whole layer).  i rolled back to rc.3 and this transparency appears to be ignored there as well.

**Comment by kneemer** [comment]
We could support that I just had not seen the value there before; only in the web map json when setting transparency to the layer.

**Comment by jgravois** [comment]
i still use desktop :smile:

**Comment by kneemer** [comment]
resolved the broken rendering, opened a new issue #57 to address layer transparency.
