### ISSUE TITLE
plugin could/should set min/maxZoom defined in service metadata automatically

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-renderers#9]
STR:
add [this](http://sampleserver6.arcgisonline.com/arcgis/rest/services/PhoneIncidents/FeatureServer/0) url as a FeatureLayer to comparisons.html.

notice that Esri Leaflet draws the graphics at all scale ranges, while it is neccessary to zoom in past 1:150000 in the sample JSAPI app.

support for setting min/maxZoom programmatically was [added](https://github.com/Esri/esri-leaflet/pull/413) to core recently.  i think it'd be cool if this plugin set the appropriate properties dynamically.

let me know if you agree.  if so, i'm happy to tackle.

**Comment by alaframboise** [comment]
Hey guys, sorry for chiming in late here, but here's a few additional thoughts. If a user takes the time to set the renderer symbology for a FeatureLayer (most likely by using the Map Viewer) then they mostly likely took time to set the zoom levels too. There's definitely a solid usability relationship between the two and it's definitely frustrating when client apis don't respect those meta settings. I just went through this whole exercise on a [recent project](http://jsbin.com/jawibo/1) and ran into the zoom level [limitation](http://jsbin.com/laxotu/1) with esri-leaflet. Therefore, it definitely feels a little strange that this functionality 1) wouldn't be built into core as an optional setting (true by default), or 2) it wouldn't be built into this repo since symbols and zoom levels are so closely related. A whole plugin just to toggle layers on and off?

**Comment by kneemer** [comment]
The advantage of putting it in a separate plugin is that it can be built and maintained separate from either esri-leaflet or this plugin.  Then when we decide which one it belongs in we just include it in the build process so that the user only needs to worry about one plugin.  I like the idea of 'micro' plugins as it keeps the core functionality of the original plugin cleaner.

**Comment by patrickarlt** [comment]
I think we are all talking around 2 different problems here.

1. Automatically using min/max zoom from the service metadata for `FeatureLayers` this is what @kneemer and @jgravois have been discussing
2. Automatically using min/max zoom from the service metadata for `TileLayers` this is the problem that @alaframboise had (since Esri Leaflet only updated the dark gray basemap yesterday)

Building this into the base of the library seems problematic because it adds a lot of complexity, mostly because layer drawing is controlled based on min/max zoom and we have to check if its with range before drawing. Its another request and adds a decent amount of complexity and it means we have to delay drawing for another round trip.

Leaflet also doesn't support dynamically setting the min/max zoom after the fact. It only checks it at the time you add the layer to the map. So in addition to having to alter the drawing code we also have to use some of the internal methods to update the zoom range which seems a bit messy.

 Maybe a better way around this is to wrap creating the proper options object from the metadata as a helper method for users.

```js
// the getOptions comes from a plugin
L.esri.FeatureLayer.getOptions(url, function(error, options){
  L.esri.featureLayer(url, options).addTo(map);
});
```
